#PBS -S /bin/csh
#PBS -V
#PBS -q normal 
#PBS -lselect=56:ncpus=128:mpiprocs=128:model=rom_ait,walltime=08:00:00
#PBS -W group_list=s2832
#PBS -j oe
#PBS -o /nobackupp12/grleung1/basinlcc/b2_test/ 
#PBS -N basinlcc.b2_test.init
#PBS -m be
#PBS -r n

setenv MPI_TYPE_DEPTH 16
module load gcc/10.3 mpi-hpe/mpt.2.25 comp-intel/2020.4.304 szip/2.1.1
#limit coredumpsize unlimited

cd /home6/grleung1/basinlcc-rams/run/b2_test/

# HDF5 Library
setenv LD_LIBRARY_PATH /home6/grleung1/misc/hdf5-1.10.8-build/lib:$LD_LIBRARY_PATH
# ZFP Library
setenv LD_LIBRARY_PATH /home6/grleung1/misc/zfp/lib:$LD_LIBRARY_PATH
# HDF5 ZFP Library
setenv LD_LIBRARY_PATH /home6/grleung1/misc/H5Z-ZFP-build/lib:$LD_LIBRARY_PATH
# HDF5 Plugin path
setenv HDF5_PLUGIN_PATH /home6/grleung1/misc/H5Z-ZFP-build/plugin

mpiexec ./rams-6.3.02 -f ./RAMSIN.b2_test.INIT >& /nobackupp12/grleung1/basinlcc/b2_test/out-past/rams_01.log

